[workspace]
members = ["crates/eth", "crates/sol", "crates/veil", "crates/storage", "crates/sdk", "crates/wallet-cli"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "BSD-3-Clause"
repository = "https://github.com/Interveil/wallet-sdk"
authors =  ["Lika"]

[patch.crates-io]
sdk = { path = "crates/sdk" }
eth = { path = "crates/eth" }
sol = { path = "crates/sol" }
veil = { path = "crates/veil" }
storage = { path = "crates/storage" }
